const defaultParams = [
  {
    param_key: "Produto",
    required: false,
    keywords: [
      "material enviado",
      "amostra",
      "peça",
      "peça cirúrgica",
      "fragmentos",
      "biópsia",
      "biopsia",
      "espécime",
      "especime",
      "exame anatomopatológico",
      "histopatologia",
      "material recebido",
    ],
    values: [
      {
        value: "Biópsia",
        keywords: [
          "biópsia",
          "biopsia",
          "core biopsy",
          "tru-cut",
          "trucut",
          "punch biopsy",
          "fna",
          "paaf",
          "fragmento",
          "cilindro",
          "tissue biopsy",
          "specimen biopsy",
        ],
      },
      {
        value: "Peça cirúrgica",
        keywords: [
          "peça cirúrgica",
          "peça operatória",
          "ressecção",
          "resection specimen",
          "excisão",
          "mastectomia",
          "quadrantectomia",
          "histerectomia",
          "prostatectomia",
          "nefrectomia",
          "lobectomia",
          "orgão ressecado",
          "tecido ressecado",
        ],
      },
    ],
  },
  {
    param_key: "Tumor primário",
    required: true,
    keywords: [
      "tumor primário",
      "tumor primario",
      "primário",
      "primario",
      "primary tumor",
      "primary",
      "origem tumoral",
      "localização primária",
      "localizacao primaria",
      "sítio primário",
      "sitio primario",
      "neoplasia primária",
      "neoplasia primaria",
      "tumor inicial",
      "carcinoma primário",
      "carcinoma primario",
    ],
    values: [
      {
        value: "Mama",
        keywords: [
          "mama",
          "breast",
          "carcinoma da mama",
          "tumor mamário",
          "tumor mamario",
        ],
      },
      {
        value: "Estômago",
        keywords: [
          "estômago",
          "estomago",
          "gastrico",
          "gástrico",
          "gastric",
          "adenocarcinoma gástrico",
          "adenocarcinoma gastrico",
        ],
      },
      {
        value: "Cólon e recto",
        keywords: [
          "cólon",
          "colon",
          "recto",
          "reto",
          "colorectal",
          "colorretal",
          "intestino grosso",
          "adenocarcinoma colorretal",
        ],
      },
      {
        value: "Endométrio",
        keywords: [
          "endométrio",
          "endometrio",
          "uterino",
          "uterus",
          "endometrial",
        ],
      },
      {
        value: "Colo do útero",
        keywords: [
          "colo do útero",
          "colo do utero",
          "cervical",
          "cérvix",
          "cervix",
          "carcinoma cervical",
        ],
      },
      {
        value: "Ovário",
        keywords: [
          "ovário",
          "ovario",
          "ovariano",
          "ovarian",
          "carcinoma do ovário",
        ],
      },
      {
        value: "Outro",
        keywords: [
          "outro",
          "outros",
          "não especificado",
          "nao especificado",
          "unknown",
          "indeterminado",
        ],
      },
    ],
  },
  {
    param_key: "Origem da amostra",
    required: true,
    keywords: [
      "origem da amostra",
      "local da amostra",
      "tipo de amostra",
      "fonte da amostra",
      "procedencia da amostra",
      "origem do material",
      "fonte do material",
      "local de colheita",
      "site da amostra",
      "sample origin",
      "sample source",
      "specimen source",
      "specimen origin",
      "tumor origin",
      "site of biopsy",
      "anatomical site",
      "primary site",
    ],
    values: [
      {
        value: "Tumor primário",
        keywords: [
          "tumor primario",
          "primario",
          "lesao primaria",
          "neoplasia primaria",
          "tumor inicial",
          "primary tumor",
          "primary lesion",
          "primary neoplasm",
          "tumor primitivo",
        ],
      },
      {
        value: "Metástase ao diagnóstico",
        keywords: [
          "metastase ao diagnostico",
          "metastatico ao diagnostico",
          "doenca metastatica inicial",
          "metastase inicial",
          "metastase sincrona",
          "doenca disseminada ao diagnostico",
          "metastatic at diagnosis",
          "de novo metastatic",
          "synchronous metastasis",
          "stage iv at diagnosis",
        ],
      },
      {
        value: "Recidiva",
        keywords: [
          "recidiva",
          "recorrencia",
          "recaida",
          "retorno da doenca",
          "doenca recorrente",
          "tumor recorrente",
          "recurrente",
          "recurrence",
          "relapse",
          "recurrent disease",
          "tumor recurrence",
          "local recurrence",
        ],
      },
    ],
  },

  {
    param_key: "Percentagem de células com expressão",
    required: true,
    keywords: [
      "percentagem",
      "%",
      "células positivas",
      "expressão tumoral",
      "tps",
      "cps",
      "tumor proportion score",
      "combined positive score",
    ],
    values: [],
  },

  {
    param_key: "Critérios de interpretação",
    required: true,
    keywords: [
      "critérios",
      "interpretação",
      "guideline",
      "asco",
      "cap",
      "esmo",
    ],
    values: [
      {
        value: "ASCO/CAP",
        keywords: ["asco", "cap", "asco/cap"],
      },
      {
        value: "Outro",
        keywords: ["outro", "interno", "local"],
      },
    ],
  },

  {
    param_key: "Resultado",
    keywords: [
      "resultado",
      "resultado final",
      "resultado ihc",
      "resultado her2",
      "classificacao",
      "score",
      "score her2",
      "interpretacao",
      "conclusao",
      "status her2",
      "expressao her2",
      "avaliacao her2",
      "perfil her2",
      "resultado imunohistoquimica",
      "ihc",
      "her2",
      "her-2",
      "her 2",
      "her2/neu",
      "her-2/neu",
      "c-erbb-2",
      "c-erbb2",
      "cerbb2",
      "cerb-2",
      "erb-b2",
      "erbb2",
    ],
    values: [
      {
        value: "Negativo (0)",
        keywords: [
          "negativo",
          "0",
          "score 0",
          "0+",
          "her2 0",
          "sem expressao",
          "ausencia de expressao",
          "nao expresso",
          "expressao ausente",
          "negative",
        ],
      },
      {
        value: "1+",
        keywords: [
          "1+",
          "score 1+",
          "her2 1+",
          "baixo positivo",
          "fraca expressao",
          "expressao fraca",
          "weak staining",
        ],
      },
      {
        value: "2+",
        keywords: [
          "2+",
          "score 2+",
          "her2 2+",
          "equivoco",
          "equivocal",
          "borderline",
          "indeterminado",
          "duvidoso",
          "inconclusivo",
        ],
      },
      {
        value: "3+",
        keywords: [
          "3+",
          "score 3+",
          "her2 3+",
          "positivo",
          "fortemente positivo",
          "superexpressao",
          "overexpression",
          "expressao intensa",
          "positive",
        ],
      },
      {
        value: "Inadequado",
        keywords: [
          "inadequado",
          "nao avaliavel",
          "insuficiente",
          "material insuficiente",
          "amostra insuficiente",
          "nao interpretavel",
          "inconclusivo por material",
          "teste invalido",
          "uninterpretable",
          "invalid",
        ],
      },
      {
        value: "Amplificado (SISH)",
        keywords: [
          "amplificado",
          "her2 amplificado",
          "gene amplification",
          "sish positivo",
          "fish positivo",
        ],
      },
      {
        value: "Não amplificado (SISH)",
        keywords: [
          "nao amplificado",
          "her2 nao amplificado",
          "no amplification",
          "sish negativo",
          "fish negativo",
        ],
      },
    ],
  },
];

export default defaultParams;
