const endpoints = {
  publicStats: {
    overview: "/publicStats/overview",
    registry: "/publicStats/registry",
  },
  auth: {
    login: "/auth/login",
    verifyToken: "/auth/verifyToken",
    verifyUser: "/auth/verifyUser",
    forgotPassword: "/auth/forgotPassword",
    resetPassword: "/auth/resetPassword",
    generatePassword: "/auth/generatePassword",
    update: "/auth/update",
  },
  patient: {
    read: "/patient/read",
    readById: "/patient/readById",
    readByInstitution: "/patient/readByInstitution",
    update: "/patient/update",
    create: "/patient/create",
    delete: "/patient/delete",
  },
  logs: {
    read: "/logs/read",
    readByHospital: "/logs/readByHospital",
    create: "/logs/create",
  },
  icd: {
    read: "/icd/read",
    readByFilter: "/icd/readByFilter",
    update: "/icd/update",
    create: "/icd/create",
    delete: "/icd/delete",
  },
  submissionPDL1: {
    read: "/submission/read",
    readByFilter: "/submission/readByFilter",
    update: "/submission/update",
    readPDF: "/submission/readPDF",
    readExcel: "/submission/readExcel",
    delete: "/submission/delete",
    create: "/submission/create",
  },
  submissionHer: {
    read: "/submissionHer/read",
    readLastByHospital: "/submissionHer/readLastByHospital",
    readProcessByHospital: "/submissionHer/readProcessByHospital",
    update: "/submissionHer/update",
    readPDF: "/submissionHer/readPDF",
    readExcel: "/submissionHer/readExcel",
    delete: "/submissionHer/delete",
    create: "/submissionHer/create",
    checkExisting: "/submissionHer/checkExisting",
    keysValues: "/submissionHer/keysValues",
  },
  paramsHer: {
    read: "/paramsHer/params",
    update: "/paramsHer/params/:param_id",
    delete: "/paramsHer/params/:param_id",
    fullCreate: "/paramsHer/full",
  },

  paramsValuesHer: {
    create: "/paramsHer/values/:param_id",
    update: "/paramsHer/values/:value_id",
    delete: "/paramsHer/values/:value_id",
  },
  processHer: {
    read: "/processHer/read",
    readByHospital: "/processHer/readByHospital",
  },
  hospital: {
    read: "/hospital/read",
    readById: "/hospital/readById",
    update: "/hospital/update",
    delete: "/hospital/delete",
    create: "/hospital/create",
    // technical
    readTechnicalByHospital: "/hospital/technical/readByHospital",
    readTechnical: "/hospital/technical/read",
    saveTechnical: "/hospital/technical/save",
    deleteTechnical: "/hospital/technical/delete",
    defaultTechnical: "/hospital/technical/default",
  },
  repHospital: {
    read: "/repHospital/read",
    readById: "/repHospital/readById",
    generatePassword: "/repHospital/generatePassword",
    readByHospital: "/repHospital/readByHospital",
    update: "/repHospital/update",
    delete: "/repHospital/delete",
    create: "/repHospital/create",
  },
  statistics: {
    hospitalsCount: "/statistics/hospitalsCount",
    submissionsCount: "/statistics/submissionsCount",
    submissionsTodayCount: "/statistics/submissionsTodayCount",
    usersCount: "/statistics/usersCount",
    recentSubmissions: "/statistics/recentSubmissions",
    districts: "/statistics/districts",
    topPlatforms: "/statistics/topPlatforms",
    topProducts: "/statistics/topProducts",
    topClones: "/statistics/topClones",
  },
  admin: {
    read: "/admin/read",
    readById: "/admin/readById",
    update: "/admin/update",
    create: "/admin/create",
  },
  dataManagement: {
    read: "/dataManagement/read",
    stats: "/dataManagement/stats",
    pendingCount: "/dataManagement/pendingCount",
    create: "/dataManagement/create",
    update: "/dataManagement/update",
    delete: "/dataManagement/delete",
    suggest: "/dataManagement/suggest",
    approve: "/dataManagement/approve",
    reject: "/dataManagement/reject",
  },
  biomarkers: {
    read: "/biomarkers/read",
    create: "/biomarkers/create",
    update: "/biomarkers/update",
    delete: "/biomarkers/delete",
  },
};

export default endpoints;
